/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6795. Copyright MediaTek Inc. (C) 2013.
 * Thu Jul 02 08:59:17 2015
 * Do Not Modify the File.
 */

#define CUST_EINT_MD_LEVEL_SENSITIVE        0
#define CUST_EINT_MD_EDGE_SENSITIVE         1


#define PAD_INT_SIM1		0
#define PAD_INT_SIM2		1
#define PAD_SPI_MO		2
#define PAD_SPI_CS		3
#define PAD_URXD0		4
#define PAD_URTS0		5
#define PAD_URXD3		6
#define PAD_DPI_D0		7
#define PAD_DPI_D2		8


#define CUST_EINT_POLARITY_LOW              0
#define CUST_EINT_POLARITY_HIGH             1
#define CUST_EINT_EDGE_SENSITIVE            0
#define CUST_EINT_LEVEL_SENSITIVE           1




#define CUST_EINT_MD1_CNT      0


